Periodic dotfiles checkpoint
Noteable change: I think I fixed audio config. JACK, Pulse, and ALSA
configurations are working together now. **Note** Pulse must be started
manually, (in .xinitrc for instance), not through whatever systemd has
cooked up.

diff --git a/addtl/bin/sh/dlpage b/addtl/bin/sh/dlpage
--- a/addtl/bin/sh/dlpage
+++ b/addtl/bin/sh/dlpage
@@ -1,10 +1,14 @@
 #!/usr/bin/env sh
 
+# Download a web page with wget.
+
 cmd="wget -v --show-progress --timestamping --no-cookies --compression=auto \
 --adjust-extension --convert-links --page-requisites --force-directories \
 --hsts-file="$CONFIGDIR"/wget/hsts --append-output="$LOGDIR"/wget"
+# If non-zero, create files in page directories that store the url downloaded
+genlinks=0
 
-dl()
+dlpages()
 {
 	i=1
 	cnt="$#"
@@ -21,7 +25,7 @@ dl()
 		if [ -n "$pass" ]; then
 			user="$(printf "%s" "$userpass" | grep : | cut -d: -f1)"
 		else
-		    user=$userpass
+			user=$userpass
 		fi
 
 		# extract the host -- updated
@@ -30,7 +34,7 @@ dl()
 		if [ -n "$port" ]; then
 			host="$(printf "%s" "$hostport" | grep : | cut -d: -f1)"
 		else
-		    host=$hostport
+			host=$hostport
 		fi
 
 		# extract the path (if any)
@@ -39,40 +43,57 @@ dl()
 		printf "Downloading %i/%i : %s\\n" "$i" "$cnt" "$1"
 		cc="$cmd '$1'"
 		eval $cc
-		printf "%s\\n" "$1" >> "$path/link"
+		if [ "$genlinks" -ne 0 ] ; then
+			printf "%s\\n" "$1" >> "$path/link"
+			cod=$?
+			[ "$cod" -ne 0 ] && exit $cod
+		fi
 		i=$((i+1))
 		shift
 	done
 }
 
-lst=" "
+dllst=" "
 app=""
 hst=""
 cnt=0
 while [ "$#" -gt 0 ] ; do
-	if [ "$1" = "-r" ] ; then
-		cmd="$cmd --recursive -e robots=off"
+	if [ "$1" = "-L" ] ; then
+		# Toggle link generation
+		genlinks=$((1-genlinks))
+	elif [ "$1" = "-r" ] ; then
+		# Recurse for a little while
+		cmd="$cmd --recursive --execute robots=off"
 	elif [ "$1" = "-R" ] ; then
+		# Recurse downwards forever
 		cmd="$cmd --level=inf --no-parent"
 	elif [ "$1" = "-l" ] ; then
+		# Set custom log file
 		app="--append-output="$2""
 		shift
 	elif [ "$1" = "-h" ] ; then
+		# Set custom history file
 		hst="--hsts-file="$2""
 		shift
 	else
 		if [ "$1" = "" ] ; then
+			# Empty url
 			shift
 			continue
-		elif [ -z "${lst##*$1}" ] ; then
+		elif [ -z "${dllst##*$1}" ] ; then
+			# Already set for download
 			shift
 			continue
 		else
-			lst="$lst $1"
+			dllst="$dllst $1"
 			cnt=$((cnt+1))
 		fi
 	fi
 	shift
 done
+if [ "$cnt" -eq 0 ] ; then
+	echo "No urls passed"
+	exit
+fi
 cmd="$cmd $app $hst"
-dl $lst
+dlpages $dllst
diff --git a/addtl/bin/sh/setbg b/addtl/bin/sh/setbg
--- a/addtl/bin/sh/setbg
+++ b/addtl/bin/sh/setbg
@@ -1,23 +1,27 @@
 #!/usr/bin/env sh
 # Sets the background. If given an argument, will set file as background.
 
-if [ -n "$WALLDIR" ] ; then
-    DIR="$WALLDIR"
-else
-    DIR="$HOME/wallpapers/"
-fi
+dir="${WALLDIR:-$HOME/wallpapers}"
 # $1 = directory
 selectRandomFile()
 {
-    [ "$#" -eq 0 ] && exit
-    if [ -r $1 ]; then
-        echo "$(find -L $(realpath $1) -type f | shuf -n 1)"
-    else
-        echo "Please input an image file or directory"
-        exit
-    fi
+	[ "$#" -eq 0 ] && exit
+	if [ -r "$1" ]; then
+		printf "%s" "$(find -L "$(realpath "$1")" -type f | shuf -n 1)"
+	else
+		printf "invalid path '%s'" "$1"
+		return 1
+	fi
+	return 0
 }
 
-[ -n "$1" ] && DIR=$1
-echo $DIR
-xwallpaper --zoom "$(selectRandomFile $DIR)"
+[ -n "$1" ] && dir="$1"
+file="$(selectRandomFile "$dir")"
+code=$?
+if [ -d "$LOGDIR" ] ; then
+	printf "%s\\n" "$file" >> "$LOGDIR"/wallpaper
+else
+	printf "%s\\n" "$file"
+fi
+[ ! "$code" = "0" ] && exit $code
+xwallpaper --zoom "$file"
diff --git a/addtl/bin/sh/sourcemod/spbuild b/addtl/bin/sh/sourcemod/spbuild
--- a/addtl/bin/sh/sourcemod/spbuild
+++ b/addtl/bin/sh/sourcemod/spbuild
@@ -4,50 +4,55 @@
 # $2 - output directory; defaults to "$PWD/compiled"
 
 input=""
-outdir="${PWD}/compiled"
+outdir="${2:-"$PWD/compiled"}"
 errfile="errors"
 
 # First arg
 if [ -n "$1" ] ; then
-    if [ -e "$1" ] ; then
-        input="$(realpath $1)"
-    else
-        printf "%s\n" "$1: No such file or directory"
-        exit 1
-    fi
+	if [ -e "$1" ] ; then
+		input="$(realpath $1)"
+	else
+		printf "%s: No such file or directory\\n" "$1"
+		exit 1
+	fi
 else
-    printf "%s\n" "No file or directory passed"
-    exit 2
+	printf "No file or directory passed\\n"
+	exit 2
 fi
 
-# Second arg
-if [ -n "$2" ] ; then
-    outdir="$(realpath -m $2)"
-fi
 # Output directory verification
-printf "%s\n" "Output directory: $outdir"
 if [ ! -e $outdir ] ; then
-    if mkdir $outdir ; then
-        printf "%s\n" "Created directory: $outdir"
-    else
-        printf "%s\n" "Error creating directory $outdir"
-        exit 3
-    fi
+	if mkdir -p $outdir ; then
+		printf "Created output directory: '%s'\\n" "$outdir"
+	else
+		printf "Could not create output directory '%s'\\n" "$outdir"
+		exit 3
+	fi
+else
+	printf "Using output directory '%s'\\n" "$outdir"
 fi
 # Compilation
 # TODO: Turn the compilation step into a function
 #       Also consider making it so compiling a directory
 #           replicates the directory structure in the build directory
+
+compile()
+{
+	# $1=sourcefile
+	# $2=outdir
+	smxfile=
+}
+
 if [ -d $input ] ; then
-    for sourcefile in $input/*.sp ; do
-        smxfile="$(printf "%s" "$(basename $sourcefile).smx" | sed 's/\(.*\)\.sp/\1/')"
-        outfile="${outdir}/${smxfile}"
-        printf "%s\n" "Compilling $(basename $sourcefile) to $(basename $outfile)"
-        spcomp $sourcefile -o$outfile
-    done
+	for sourcefile in $input/*.sp ; do
+		smxfile="$(printf "%s" "$(basename $sourcefile).smx" | sed 's/\(.*\)\.sp/\1/')"
+		outfile="${outdir}/${smxfile}"
+		printf "%s\\n" "Compilling $(basename $sourcefile) to $(basename $outfile)"
+		spcomp $sourcefile -o$outfile
+	done
 else
-    smxfile="$(printf "%s" "$(basename $input).smx" | sed 's/\(.*\)\.sp/\1/')"
-    outfile="${outdir}/${smxfile}"
-    printf "%s\n" "Compilling $(basename $input) to $(basename $outfile)"
-    spcomp $input -o$outfile
+	smxfile="$(printf "%s" "$(basename $input).smx" | sed 's/\(.*\)\.sp/\1/')"
+	outfile="${outdir}/${smxfile}"
+	printf "%s\\n" "Compilling $(basename $input) to $(basename $outfile)"
+	spcomp $input -o$outfile
 fi
