Woohoo checkpoint!
I've got a vim plugin that's not been added yet, will add at some point.

diff --git a/addtl/bin/sh/extract b/addtl/bin/sh/extract
--- a/addtl/bin/sh/extract
+++ b/addtl/bin/sh/extract
@@ -4,75 +4,104 @@
 # Default behavior: Extract archive into new directory
 # Behavior with `-c` option: Extract contents into current directory
 
+do_help ()
+{
+  printf "Options:\\n"
+  printf "   -c: Extract archive into current directory rather than a subdirectory.\\n"
+  printf "   -o DIR: Place output in DIR\\n"
+  exit 0
+}
+
 _name="$(basename "$0")"
 
-_extract_here=0
-while getopts "hc" o; do case "${o}" in
-	c) _extract_here=1 && shift 1;;
-	*) printf "Options:\\n   -c: Extract archive into current directory rather than a new one.\\n" && exit ;;
-esac done
+_use_subdir=1
+_outdir="."
+while [ "$#" -gt 0 ]; do
+  _should_break=0
+  case "$1" in
+    -c)
+      _use_subdir=$((1 - _use_subdir))
+      shift 1;;
+    -o)
+      if [ "$#" -gt 1 ]; then
+        _outdir="$2"
+        shift 2
+      else
+        printf "Must specify DIR for '-o'\\n"
+        do_help
+      fi
+      ;;
+    *) _should_break=1;;
+  esac
+  if [ "$_should_break" -ne "0" ]; then
+    break
+  fi
+done
 
 N=0
 for i in "$@" ; do
-	# Absolute filepath
-	_archive="$(realpath -m "$i")"
-	_name="$(basename "$_archive")"
-	_directory="$(dirname "$_archive")"
-	_subdirectory="$_directory/"$_name"_out"
-	if [ ! -e "$_archive" ] ; then
-		printf "%s: Could not extract '%s': Could not find '%s'\\n" "$_name" "$i" "$_archive"
-		continue
-	elif [ ! -f "$_archive" ] ; then
-		printf "%s: Can't extract '%s': Not a regular file '%s'\\n" "$_name" "$i" "$_archive"
-		continue
-	fi
+  # Absolute filepath
+  _archive="$(realpath -m "$i")"
+  _name="$(basename "$_archive")"
+  _directory="$(dirname "$_archive")"
+  if [ "$_use_subdir" -ne 0 ]; then
+    _subdirectory="$directory/${_name}_out"
+  else
+    _subdirectory="$directory"
+  fi
+  _output="$(realpath -m --relative-to "$PWD" "$_outdir/$_subdirectory")"
+  if [ ! -e "$_archive" ] ; then
+    printf "%s: Could not extract '%s': Could not find '%s'\\n" "$_name" "$i" "$_archive"
+    continue
+  elif [ ! -f "$_archive" ] ; then
+    printf "%s: Can't extract '%s': Not a regular file '%s'\\n" "$_name" "$i" "$_archive"
+    continue
+  fi
 
-	N=$((N+1))
-	printf "Extracting %d/%d: %s\\n" "$N" "$#" "$i"
-	if [ -f "$_archive" ] ; then
-		case "$_archive" in
-			*.tar.bz2|*.tar.xz|*.tbz2)
-				cmd="tar xvjf" ;;
-			*.tar.gz|*.tgz)
-				cmd="tar xvzf" ;;
-			*.lzma)
-				cmd="unlzma" ;;
-			*.bz2)
-				cmd="bunzip2" ;;
-			*.rar)
-				cmd="unrar x" ;;
-			*.gz)
-				cmd="gunzip" ;;
-			*.tar)
-				cmd="tar xvf" ;;
-			*.zip)
-				cmd="unzip" ;;
-			*.Z)
-				cmd="uncompress" ;;
-			*.7z|*.iso)
-				cmd="7z x" ;;
-			*.xz)
-				cmd="unxz" ;;
-			*.exe)
-				cmd="cabextract" ;;
-			*)
-				printf "%s: '%s' - unknown archive method\\n" "$_name" "$_archive"
-				continue ;;
-		esac
+  N=$((N+1))
+  printf "Extracting %d/%d: %s\\n" "$N" "$#" "$i"
+  if [ -f "$_archive" ] ; then
+    case "$_archive" in
+      *.tar.bz2|*.tar.xz|*.tbz2)
+        cmd="tar xvjf" ;;
+      *.tar.gz|*.tgz)
+        cmd="tar xvzf" ;;
+      *.lzma)
+        cmd="unlzma" ;;
+      *.bz2)
+        cmd="bunzip2" ;;
+      *.rar)
+        cmd="unrar x" ;;
+      *.gz)
+        cmd="gunzip" ;;
+      *.tar)
+        cmd="tar xvf" ;;
+      *.zip)
+        cmd="unzip" ;;
+      *.Z)
+        cmd="uncompress" ;;
+      *.7z|*.iso)
+        cmd="7z x" ;;
+      *.xz)
+        cmd="unxz" ;;
+      *.exe)
+        cmd="cabextract" ;;
+      *)
+        printf "%s: '%s' - unknown archive method\\n" "$_name" "$_archive"
+        continue ;;
+    esac
 
-		if [ "$_extract_here" -eq 0 ] ; then
-			if [ -e "$_subdirectory" ] ; then
-				printf "%s: '%s' already exists.\\n" "$_name" "$_subdirectory"
-				continue
-			fi
-			mkdir -p "$_subdirectory" || exit
-			cd "$_subdirectory"
-		fi
-		$cmd "$_archive"
-		if [ "$_extract_here" -ne 0 ] ; then
-			cd -
-		fi
-	else
-		printf "%s: File '%s' not found.\\n" "$_name" "$_archive"
-	fi
+    if [ "$_use_subdir" -ne 0 ]; then
+      if [ -e "$_output" ]; then
+        printf "%s: '%s' already exists.\\n" "$_name" "$_output"
+        continue
+      fi
+    fi
+    mkdir -p "$_output" || exit
+    cd "$_output"
+    $cmd "$_archive"
+    cd -
+  else
+    printf "%s: File '%s' not found.\\n" "$_name" "$_archive"
+  fi
 done
diff --git a/addtl/bin/sh/image/rszimg b/addtl/bin/sh/image/rszimg
--- a/addtl/bin/sh/image/rszimg
+++ b/addtl/bin/sh/image/rszimg
@@ -1,27 +1,30 @@
 #!/usr/bin/env sh
+# Resizes images using imagemagick
+echo "Please just do this manually"
+exit 1
 
 # $1  = width
 # $2  = height
 # $3+ = image(s)
 
 if [ "$#" -gt 2 ] ; then
-    if [ "$1" -gt 0 ] && [ "$2" -gt 0 ] ; then
-        nw="$1" ; nh="$2"
-        shift 2
-        echo "Resizing images: $*"
-        if int "$nw" && stcpos "$nw" && int "$nh" && stcpos "$nh" ; then
-            while [ "$#" -gt 0 ] ; do
-                echo "Resizing $1"
-                convert "$1" "-resize" "${nw}x${nh}" "$1"
-                shift
-            done
-        else
-            echo "Error resising: width and height must be strictly positive integers."
-        fi
+  if [ "$1" -gt 0 ] && [ "$2" -gt 0 ] ; then
+    nw="$1" ; nh="$2"
+    shift 2
+    echo "Resizing images: $*"
+    if int "$nw" && stcpos "$nw" && int "$nh" && stcpos "$nh" ; then
+      while [ "$#" -gt 0 ] ; do
+        echo "Resizing $1"
+        convert "$1" "-resize" "${nw}x${nh}" "$1"
+        shift
+      done
     else
-        echo "Error resizing: Cannot resize image to width or height of <1."
+      echo "Error resising: width and height must be strictly positive integers."
     fi
+  else
+    echo "Error resizing: Cannot resize image to width or height of <1."
+  fi
 else
-    echo "Usage: rszimg width height image(s)"
+  echo "Usage: rszimg width height image(s)"
 fi
 
diff --git a/addtl/bin/sh/math/strictlypositive b/addtl/bin/sh/math/strictlypositive
--- a/addtl/bin/sh/math/strictlypositive
+++ b/addtl/bin/sh/math/strictlypositive
@@ -1,8 +1,8 @@
 #!/usr/bin/env sh
 
 if [ -n "$(command -v awk)" ] ; then
-	awk -v val="$1" 'BEGIN{exit !(val > 0)}'
+  awk -v val="$1" 'BEGIN{exit !(val > 0)}'
 else
-	echo "awk is not installed, cannot do comparison"
-	exit 1
+  echo "awk is not installed, cannot do comparison"
+  exit 1
 fi
diff --git a/addtl/bin/sh/sourcemod/spbuild b/addtl/bin/sh/sourcemod/spbuild
--- a/addtl/bin/sh/sourcemod/spbuild
+++ b/addtl/bin/sh/sourcemod/spbuild
@@ -9,27 +9,27 @@ errfile="errors"
 
 # First arg
 if [ -n "$1" ] ; then
-	if [ -e "$1" ] ; then
-		input="$(realpath $1)"
-	else
-		printf "%s: No such file or directory\\n" "$1"
-		exit 1
-	fi
+  if [ -e "$1" ] ; then
+    input="$(realpath $1)"
+  else
+    printf "%s: No such file or directory\\n" "$1"
+    exit 1
+  fi
 else
-	printf "No file or directory passed\\n"
-	exit 2
+  printf "No file or directory passed\\n"
+  exit 2
 fi
 
 # Output directory verification
 if [ ! -e $outdir ] ; then
-	if mkdir -p $outdir ; then
-		printf "Created output directory: '%s'\\n" "$outdir"
-	else
-		printf "Could not create output directory '%s'\\n" "$outdir"
-		exit 3
-	fi
+  if mkdir -p $outdir ; then
+    printf "Created output directory: '%s'\\n" "$outdir"
+  else
+    printf "Could not create output directory '%s'\\n" "$outdir"
+    exit 3
+  fi
 else
-	printf "Using output directory '%s'\\n" "$outdir"
+  printf "Using output directory '%s'\\n" "$outdir"
 fi
 # Compilation
 # TODO: Turn the compilation step into a function
@@ -38,21 +38,21 @@ fi
 
 compile()
 {
-	# $1=sourcefile
-	# $2=outdir
-	smxfile=
+  # $1=sourcefile
+  # $2=outdir
+  smxfile=
 }
 
 if [ -d $input ] ; then
-	for sourcefile in $input/*.sp ; do
-		smxfile="$(printf "%s" "$(basename $sourcefile).smx" | sed 's/\(.*\)\.sp/\1/')"
-		outfile="${outdir}/${smxfile}"
-		printf "%s\\n" "Compilling $(basename $sourcefile) to $(basename $outfile)"
-		spcomp $sourcefile -o$outfile
-	done
+  for sourcefile in $input/*.sp ; do
+    smxfile="$(printf "%s" "$(basename $sourcefile).smx" | sed 's/\(.*\)\.sp/\1/')"
+    outfile="${outdir}/${smxfile}"
+    printf "%s\\n" "Compilling $(basename $sourcefile) to $(basename $outfile)"
+    spcomp $sourcefile -o$outfile
+  done
 else
-	smxfile="$(printf "%s" "$(basename $input).smx" | sed 's/\(.*\)\.sp/\1/')"
-	outfile="${outdir}/${smxfile}"
-	printf "%s\\n" "Compilling $(basename $input) to $(basename $outfile)"
-	spcomp $input -o$outfile
+  smxfile="$(printf "%s" "$(basename $input).smx" | sed 's/\(.*\)\.sp/\1/')"
+  outfile="${outdir}/${smxfile}"
+  printf "%s\\n" "Compilling $(basename $input) to $(basename $outfile)"
+  spcomp $input -o$outfile
 fi
