Cleaned up bash.funcs; fixed sh math functions to return false and error if bc is not installed

diff --git a/addtl/bin/sh/math/nonnegative b/addtl/bin/sh/math/nonnegative
--- a/addtl/bin/sh/math/nonnegative
+++ b/addtl/bin/sh/math/nonnegative
@@ -1,3 +1,8 @@
 #!/usr/bin/env sh
 
-[ -n "$1" ] && [ "$(echo "($1) < 0" | bc)" -eq 0 ]
+if [ -n "$(command -v bc)" ] ; then
+	[ -n "$1" ] && [ "$(echo "($1) < 0" | bc)" -eq 0 ]
+else
+	echo "bc is not installed, cannot do comparison"
+	exit 1
+fi
